language: cpp
branches:
  only:
  - master
before_script:
- curl https://bazel.build/bazel-release.pub.gpg | sudo apt-key add -
- echo "deb [arch=amd64] https://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list
- sudo apt update && sudo apt install bazel
script:
- bazel test --host_force_python=PY2 ...
- bazel build --host_force_python=PY2 :deb-package
- mv bazel-bin/helloworld_0.0.0_amd64.deb helloworld_0.0.$TRAVIS_BUILD_NUMBER_amd64.deb
deploy:
  provider: script
  skip_cleanup: true
  script:
  - curl -T helloworld_0.0.$TRAVIS_BUILD_NUMBER_amd64.deb -ualexey-ulashchick:$BINTRAY_API_KEY "https://api.bintray.com/content/alexey-ulashchick/otus-cpp/homework-1/$TRAVIS_BUILD_NUMBER/helloworld_0.0.$TRAVIS_BUILD_NUMBER_amd64.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"
